### ISSUE TITLE
How to save cropped image as file?

### ISSUE THREAD

**Issue by clirimfurriku** [xclud/flutter_crop#10]
Is there a way to save the cropped image as file on local storage for later use?

**Comment by xclud** [comment]
I just updated the example project with saved to gallery functionality. Please check it out.

Don't forget to update `AndroidManifest.xml` file (there are 3 of them for `debug`, `profile` and `main`) and make sure write to storage is given:

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`

Please let me know if your problem is solved.

**Comment by clirimfurriku** [comment]
Yes, it works. Thank you :)
